### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sancelot** [polyhobbyist/babylon_ros#6]
Hi,
I would be interested in using that api to display and drive a robot with a ccd ik solver in a babylonjs app - NON ROS.

Is it possible to use it ?

**Comment by polyhobbyist** [comment]
HI @sancelot,
Thank you for your interest in this project!

The Babylon ROS Project is dedicated to rendering ROS "URDF" models; it is not suitable for controlling a non-ROS Robot.

While I do recommend ROS and related projects as a vendor neutral method for controlling a wide range of robots, I understand the aversion to it. I avoided ROS for many years before embracing it.

You may want to take a peek at https://cylonjs.com/ or https://johnny-five.io/, which would interface nicely with babylon.js. Alternatively, I'm a huge fan of [DeviceScript](https://microsoft.github.io/devicescript/intro) (I'm friends with the authors); and I've considered how to interface with device script robots.

I hope this helps!
